#!/bin/bash

set -euo pipefail
[ -n "${DEBUG:-}" ] && set -x

export PYTHON="python${TRAVIS_PYTHON_VERSION%.*}"
docker exec -e PYTHON="${PYTHON}" -e DEBUG="${DEBUG:-}" pydoop bash -c \
  "source /etc/profile && cd examples && ./run_all"
docker exec -e PYTHON="${PYTHON}" -e DEBUG="${DEBUG:-}" pydoop bash -c \
  "source /etc/profile && cd examples/avro/py && ./run"
